language: generic
sudo: false

env:
  BYOND_MAJOR="509"
  BYOND_MINOR="1318"
  MACRO_COUNT=984
  
cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
  
addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
  
install:
  - pip install --user PyYaml -q
  - pip install --user beautifulsoup4 -q

before_script:
  - chmod +x ./install-byond.sh
  - ./install-byond.sh

script:
  - shopt -s globstar
  - (! grep 'step_[xy]' maps/**/*.dmm)
  - (! find nano/templates/ -type f -exec md5sum {} + | sort | uniq -D -w 32 | grep nano)
  - (! grep -En "<\s*span\s+class\s*=\s*('[^'>]+|[^'>]+')\s*>" **/*.dm)
  - (num=`grep -E '\\\\(red|blue|green|black|b|i[^mc])' **/*.dm | wc -l`; echo "$num escapes (expecting ${MACRO_COUNT} or less)"; [ $num -le ${MACRO_COUNT} ])
  - (num=`grep -E '\WDel\(' **/*.dm | wc -l`; echo "$num Del()s (expecting 4 or less)"; [ $num -le 4 ])
  - (num=`grep -E '"/atom' **/*.dm | wc -l`; echo "$num /atom text paths (expecting 2 or less)"; [ $num -le 2 ])
  - (num=`grep -E '"/area' **/*.dm | wc -l`; echo "$num /area text paths (expecting 3 or less)"; [ $num -le 3 ])
  - (num=`grep -E '"/datum' **/*.dm | wc -l`; echo "$num /datum text paths (expecting 2 or less)"; [ $num -le 2 ])
  - (num=`grep -E '"/mob' **/*.dm | wc -l`; echo "$num /mob text paths (expecting 2 or less)"; [ $num -le 2 ])
  - (num=`grep -E '"/obj' **/*.dm | wc -l`; echo "$num /obj text paths (expecting 13 or less)"; [ $num -le 13 ])
  - (num=`grep -E '"/turf' **/*.dm | wc -l`; echo "$num /turf text paths (expecting 8 or less)"; [ $num -le 8 ])
  - awk -f tools/indentation.awk **/*.dm
  - md5sum -c - <<< "2eab2bb83b8fef79c218d437e96b30df *.gitignore"
  - md5sum -c - <<< "0af969f671fba6cf9696c78cd175a14a *baystation12.int"
  - md5sum -c - <<< "88490b460c26947f5ec1ab1bb9fa9f17 *html/changelogs/example.yml"
  - python tools/TagMatcher/tag-matcher.py ../..
  - python tools/GenerateChangelog/ss13_genchangelog.py html/changelog.html html/changelogs
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - cp config/example/* config/
  - scripts/dm.sh -DUNIT_TEST baystation12.dme
  - grep "0 warnings" build_log.txt
  - DreamDaemon baystation12.dmb -invisible -trusted -core 2>&1 | tee log.txt
  - grep "All Unit Tests Passed" log.txt
  - (! grep "runtime error:" log.txt)
  - (! grep 'Process scheduler caught exception processing' log.txt)
