language: generic
sudo: false
dist: trusty

env:
  global:
    BYOND_MAJOR="511"
    BYOND_MINOR="1385"

# ALL MAPS MUST BE PRESENT HERE
# IF THEY ARE NOT, YOUR BUILD WILL FAIL
  matrix:
    - TEST=CODE
    - TEST=WEB
    - TEST=MAP MAP_PATH=example
    - TEST=MAP MAP_PATH=exodus
    - TEST=MAP MAP_PATH=torch
    - TEST=MAP MAP_PATH=overmap_example

cache:
  directories:
    - tgui/node_modules
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - oracle-java8-set-default

script:
  - test/run-test.sh
