language: generic
sudo: false

env:
  BYOND_MAJOR="509"
  BYOND_MINOR="1318"
  MACRO_COUNT=1021
  
cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
  
addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
  
install:
  - pip install --user PyYaml -q
  - pip install --user beautifulsoup4 -q

before_script:
  - chmod +x ./install-byond.sh
  - ./install-byond.sh

script:
  - shopt -s globstar
  - (! grep 'step_[xy]' maps/**/*.dmm)
  - (! find nano/templates/ -type f -exec md5sum {} + | sort | uniq -D -w 32 | grep nano)
  - (! grep -E "<\s*span\s+class\s*=\s*('[^'>]+|[^'>]+')\s*>" **/*.dm)
  - (num=`grep -E '\\\\(red|blue|green|black|b|i[^mc])' **/*.dm | wc -l`; echo "$num escapes (expecting ${MACRO_COUNT} or less)"; [ $num -le ${MACRO_COUNT} ])
  - awk -f tools/indentation.awk **/*.dm
  - md5sum -c - <<< "0af969f671fba6cf9696c78cd175a14a *baystation12.int"
  - md5sum -c - <<< "88490b460c26947f5ec1ab1bb9fa9f17 *html/changelogs/example.yml"
  - python tools/TagMatcher/tag-matcher.py ../..
  - python tools/GenerateChangelog/ss13_genchangelog.py html/changelog.html html/changelogs --dry-run
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - cp config/example/* config/
  - scripts/dm.sh -DUNIT_TEST baystation12.dme
  - grep "0 warnings" build_log.txt
  - DreamDaemon baystation12.dmb -invisible -trusted -core 2>&1 | tee log.txt
  - grep "All Unit Tests Passed" log.txt
  - (! grep "runtime error:" log.txt)
  - (! grep 'Process scheduler caught exception processing' log.txt)
