name: Отмена

permissions:
  contents: read

on:
  push:
    branches:
      - dev
      - dev220

# NB: We can discover workflow IDs for this job at https://api.github.com/repos/ORG/REPO/actions/workflows
jobs:
  cancel:
    name: 'Отмена избыточных билдов'
    permissions:
      actions: write # required to cancel other actions
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@b173b6ec0100793626c2d9e6b90435061f4fc3e5
        with:
          workflow_id: 48054016
          access_token: ${{ github.token }}
