name: Compile changelogs

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  CompileCL:
    runs-on: ubuntu-latest
    if: github.repository == 'Baystation12/Baystation12' # to prevent this running on forks
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          fetch-depth: 0 # Otherwise, we will fail to push refs
          ref: dev
          token: ${{ secrets.BOT_TOKEN }}
      - name: Python setup
        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6
        with:
          python-version: '3.x'
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml bs4
      - name: Compile CL
        run: |
          python tools/changelog/ss13_genchangelog.py html/changelog.html html/changelogs
      - name: Commit And Push
        run: |
          git config --global user.email "${{ secrets.BOT_EMAIL }}"
          git config --global user.name "${{ secrets.BOT_NAME }}"
          git diff --quiet --exit-code && echo "No changes found, abort." && exit 0
          git commit -m "Automatic changelog generation" -a
          git push
