name: "Чейнджлог: YML -> HTML"

permissions:
  contents: read

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # allows this workflow to be manually triggered

jobs:
  CompileCL:
    permissions:
      contents: write # required to push the updated changelog commit
    runs-on: ubuntu-latest
    if: github.repository == 'SierraBay/SierraBay12' # to prevent this running on forks
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          fetch-depth: 0 # Otherwise, we will fail to push refs
          ref: dev-sierra
          token: ${{ secrets.BOT_TOKEN }}
      - name: Python setup
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: '3.x'
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml bs4
      - name: Compile CL
        run: |
          python tools/changelog/ss13_genchangelog.py html/changelog.html html/changelogs
      - name: Commit And Push
        run: |
          git config --global user.email "${{ secrets.BOT_EMAIL }}"
          git config --global user.name "${{ secrets.BOT_NAME }}"
          git diff --quiet --exit-code && echo "No changes found, abort." && exit 0
          git commit -m "Автоматическая компиляция чейнджлогов [ci skip]" -a
          git push
