name: Проверка Ченджлога

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  pull_request_target:
    types: [opened, reopened, edited]

jobs:
  CheckCL:
    runs-on: ubuntu-latest
    if: github.repository == 'SierraBay/SierraBay12' && github.base_ref == 'dev-sierra' && github.event.pull_request.draft == false
    steps:
      - name: Скачивание файлов
        run: |
          wget https://raw.githubusercontent.com/SierraBay/SierraBay12/dev-sierra/tools/changelog/sierra_check_changelog.py
          wget https://raw.githubusercontent.com/SierraBay/SierraBay12/dev-sierra/tools/changelog/tags.yml
      - name: Установка Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: '3.x'
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml PyGithub
      - name: Проверка чейнджлога
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python sierra_check_changelog.py
