name: Generate Documentation

permissions:
  contents: read

on:
  push:
    branches:
    - dev
  workflow_dispatch: # allows this workflow to be manually triggered

env:
  SPACEMAN_DMM_VERSION: suite-1.7.3

jobs:
  PreFlight:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - name: paths-filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: .github/workflow-config/preflight-filters.yml
    outputs:
      dm: ${{ steps.filter.outputs.dm }}
  generate_documentation:
    permissions:
      contents: write # required to push the doc commit
    runs-on: ubuntu-latest
    needs: PreFlight
    if: |
      (needs.PreFlight.outputs.dm == 'true') &&
      !contains(github.event.head_commit.message, '[ci skip]')
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - name: Setup Cache
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319
        with:
          path: ~/spaceman_dmm/${{ env.SPACEMAN_DMM_VERSION }}
          key: ${{ runner.os }}-spacemandmm-${{ env.SPACEMAN_DMM_VERSION }}
      - name: Install dmdoc
        run:  scripts/install-spaceman-dmm.sh dmdoc
      - name: Generate documentation
        run: |
          ~/dmdoc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@5c6e9e9f3672ce8fd37b9856193d2a537941e66c
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dmdoc
          target-folder: docs
          clean: true
