name: Generate Documentation

permissions:
  contents: read

on:
  push:
    branches:
    - dev
  workflow_dispatch: # allows this workflow to be manually triggered

env:
  SPACEMAN_DMM_VERSION: suite-1.7.3

jobs:
  PreFlight:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: paths-filter
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        id: filter
        with:
          filters: .github/workflow-config/preflight-filters.yml
    outputs:
      dm: ${{ steps.filter.outputs.dm }}
  generate_documentation:
    permissions:
      contents: write # required to push the doc commit
    runs-on: ubuntu-latest
    needs: PreFlight
    if: |
      (needs.PreFlight.outputs.dm == 'true') &&
      !contains(github.event.head_commit.message, '[ci skip]')
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Setup Cache
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84
        with:
          path: ~/spaceman_dmm/${{ env.SPACEMAN_DMM_VERSION }}
          key: ${{ runner.os }}-spacemandmm-${{ env.SPACEMAN_DMM_VERSION }}
      - name: Install dmdoc
        run:  scripts/install-spaceman-dmm.sh dmdoc
      - name: Generate documentation
        run: |
          ~/dmdoc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@a1ea191d508feb8485aceba848389d49f80ca2dc
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dmdoc
          target-folder: docs
          clean: true
