name: Generate Documentation

on:
  push:
    branches:
    - dev
  workflow_dispatch:

env:
  SPACEMAN_DMM_VERSION: suite-1.7.2

jobs:
  generate_documentation:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    concurrency: gen-docs
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: Setup Cache
        uses: actions/cache@4b0cf6cc4619e737324ddfcec08fff2413359514
        with:
          path: $HOME/spaceman_dmm/$SPACEMAN_DMM_VERSION
          key: ${{ runner.os }}-spacemandmm-${{ env.SPACEMAN_DMM_VERSION }}
      - name: Install dmdoc
        run:  scripts/install-spaceman-dmm.sh dmdoc
      - name: Generate documentation
        run: |
          ~/dmdoc
          touch dmdoc/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@830e6a4f7c81743c52f3fed0ac67428feff9620a
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages-dmdoc
          single-commit: true
          folder: dmdoc
          clean: true
