name: Make changelogs

on:
  push:
    branches:
    - dev

jobs:
  MakeCL:
    runs-on: ubuntu-latest
    if: github.repository == 'Baystation12/Baystation12' # to prevent this running on forks
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          fetch-depth: 25
      - name: Python setup
        uses: actions/setup-python@7f80679172b057fc5e90d70d197929d454754a5a
        with:
          python-version: '3.x'
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml PyGithub
      - name: Make CL
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GIT_EMAIL: "${{ secrets.BOT_EMAIL }}"
          GIT_NAME: "${{ secrets.BOT_NAME }}"
        run: python tools/changelog/generate_cl.py