name: "Чейнджлог: PR -> YML"

permissions:
  contents: read

on:
  push:
    branches:
    - dev-sierra

jobs:
  MakeCL:
    permissions:
      contents: write # required to push the changelog chunk yml commit
    runs-on: ubuntu-latest
    if: github.repository == 'SierraBay/SierraBay12' # to prevent this running on forks
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 25
      - name: Python setup
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: '3.x'
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml PyGithub
      - name: Make CL
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GIT_EMAIL: "${{ secrets.BOT_EMAIL }}"
          GIT_NAME: "${{ secrets.BOT_NAME }}"
        run: python tools/changelog/generate_cl.py
