name: Make changelogs

permissions:
  contents: read

on:
  push:
    branches:
    - dev

jobs:
  MakeCL:
    permissions:
      contents: write # required to push the changelog chunk yml commit
    runs-on: ubuntu-latest
    if: github.repository == 'Baystation12/Baystation12' # to prevent this running on forks
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          fetch-depth: 25
      - name: Python setup
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: '3.x'
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml PyGithub
      - name: Make CL
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GIT_EMAIL: "${{ secrets.BOT_EMAIL }}"
          GIT_NAME: "${{ secrets.BOT_NAME }}"
        run: python tools/changelog/generate_cl.py
