name: Run Tests

permissions:
  contents: read

on:
  pull_request:
    branches: [ "dev-sierra" ]
  workflow_dispatch: # allows this workflow to be manually triggered
env:
  BYOND_MAJOR: "514"
  BYOND_MINOR: "1589"
  SPACEMAN_DMM_VERSION: suite-1.7.3
  RUST_G_REPO: "ss220-space/rust-g-tg"
  RUST_G_VERSION: "3.0.0-ss220"

jobs:
  PreFlight:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: paths-filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: .github/workflow-config/preflight-filters.yml
    outputs:
      dm: ${{ steps.filter.outputs.dm }}
  DreamChecker:
    runs-on: ubuntu-latest
    needs: PreFlight
    if: needs.PreFlight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Setup Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: ~/spaceman_dmm/${{ env.SPACEMAN_DMM_VERSION }}
          key: ${{ runner.os }}-spacemandmm-${{ env.SPACEMAN_DMM_VERSION }}
      - name: Install Dreamchecker
        run:  scripts/install-spaceman-dmm.sh dreamchecker
      - name: Run Dreamchecker
        run: ~/dreamchecker
      # - name: Run Failure Webhook
      #   env:
      #     JOB_STATUS: ${{ job.status }}
      #     WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      #     HOOK_OS_NAME: ${{ runner.os }}
      #     WORKFLOW_NAME: ${{ github.workflow }}
      #   if: ${{ failure() }}
      #   run: |
      #     wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
      #     chmod +x send.sh
      #     ./send.sh failure $WEBHOOK_URL
  Code:
    runs-on: ubuntu-latest
    needs:
    - PreFlight
    - DreamChecker
    if: needs.PreFlight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Setup Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: ~/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Install Dependencies
        run: sudo apt-get install -y uchardet
      - name: Run Tests
        env:
          TEST: CODE
        run: test/run-test.sh
      # - name: Run Failure Webhook
      #   env:
      #     JOB_STATUS: ${{ job.status }}
      #     WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      #     HOOK_OS_NAME: ${{ runner.os }}
      #     WORKFLOW_NAME: ${{ github.workflow }}
      #   if: ${{ failure() }}
      #   run: |
      #     wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
      #     chmod +x send.sh
      #     ./send.sh failure $WEBHOOK_URL
  ExampleMap:
    runs-on: ubuntu-latest
    needs:
    - PreFlight
    - DreamChecker
    if: needs.PreFlight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Setup Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: ~/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Install rust_g dependencies
        run: ./scripts/install-rust_g-dependencies.sh
      - name: Setup rust_g cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: ~/.byond/bin/librust_g.so
          key: "rust_g-${{ env.RUST_G_REPO }}-${{ env.RUST_G_VERSION }}"
      - name: Install rust_g
        run: ./scripts/install-rust_g.sh
      - name: Run Tests
        env:
          TEST: MAP
          MAP_PATH: example
        run: test/run-test.sh
      # - name: Run Failure Webhook
      #   env:
      #     JOB_STATUS: ${{ job.status }}
      #     WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      #     HOOK_OS_NAME: ${{ runner.os }}
      #     WORKFLOW_NAME: ${{ github.workflow }}
      #   if: ${{ failure() }}
      #   run: |
      #     wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
      #     chmod +x send.sh
      #     ./send.sh failure $WEBHOOK_URL
  SierraMap:
    runs-on: ubuntu-latest
    needs:
    - PreFlight
    - DreamChecker
    if: needs.PreFlight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Setup Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: ~/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Install rust_g dependencies
        run: ./scripts/install-rust_g-dependencies.sh
      - name: Setup rust_g cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: ~/.byond/bin/librust_g.so
          key: "rust_g-${{ env.RUST_G_REPO }}-${{ env.RUST_G_VERSION }}"
      - name: Install rust_g
        run: ./scripts/install-rust_g.sh
      - name: Run Tests
        env:
          TEST: MAP
          MAP_PATH: sierra
        run: test/run-test.sh
      # - name: Run Failure Webhook
      #   env:
      #     JOB_STATUS: ${{ job.status }}
      #     WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      #     HOOK_OS_NAME: ${{ runner.os }}
      #     WORKFLOW_NAME: ${{ github.workflow }}
      #   if: ${{ failure() }}
      #   run: |
      #     wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
      #     chmod +x send.sh
      #     ./send.sh failure $WEBHOOK_URL
  AwaySites:
    runs-on: ubuntu-latest
    needs:
    - PreFlight
    - DreamChecker
    if: needs.PreFlight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Setup Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: ~/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Install rust_g dependencies
        run: ./scripts/install-rust_g-dependencies.sh
      - name: Setup rust_g cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: ~/.byond/bin/librust_g.so
          key: "rust_g-${{ env.RUST_G_REPO }}-${{ env.RUST_G_VERSION }}"
      - name: Install rust_g
        run: ./scripts/install-rust_g.sh
      - name: Run Tests
        env:
          TEST: MAP
          MAP_PATH: away_sites_testing
        run: test/run-test.sh
      # - name: Run Failure Webhook
      #   env:
      #     JOB_STATUS: ${{ job.status }}
      #     WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      #     HOOK_OS_NAME: ${{ runner.os }}
      #     WORKFLOW_NAME: ${{ github.workflow }}
      #   if: ${{ failure() }}
      #   run: |
      #     wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
      #     chmod +x send.sh
      #     ./send.sh failure $WEBHOOK_URL
