name: Run Tests

permissions:
  contents: read

on:
  push:
    branches: [ "dev", "dev220" ]
  pull_request:
    branches: [ "dev", "dev220" ]
env:
  BYOND_MAJOR: "514"
  BYOND_MINOR: "1589"
  SPACEMAN_DMM_VERSION: suite-1.7.2

jobs:
  PreFlight:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: paths-filter
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        id: filter
        with:
          filters: .github/workflow-config/preflight-filters.yml
    outputs:
      dm: ${{ steps.filter.outputs.dm }}
  DreamChecker:
    runs-on: ubuntu-20.04
    needs: PreFlight
    if: needs.PreFlight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Setup Cache
        uses: actions/cache@6998d139ddd3e68c71e9e398d8e40b71a2f39812
        with:
          path: $HOME/spaceman_dmm/$SPACEMAN_DMM_VERSION
          key: ${{ runner.os }}-spacemandmm-${{ env.SPACEMAN_DMM_VERSION }}
      - name: Install Dreamchecker
        run:  scripts/install-spaceman-dmm.sh dreamchecker
      - name: Run Dreamchecker
        run: ~/dreamchecker
      # - name: Run Failure Webhook
      #   env:
      #     JOB_STATUS: ${{ job.status }}
      #     WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      #     HOOK_OS_NAME: ${{ runner.os }}
      #     WORKFLOW_NAME: ${{ github.workflow }}
      #   if: ${{ failure() }}
      #   run: |
      #     wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
      #     chmod +x send.sh
      #     ./send.sh failure $WEBHOOK_URL
  Code:
    runs-on: ubuntu-20.04
    needs:
    - PreFlight
    - DreamChecker
    if: needs.PreFlight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Setup Cache
        uses: actions/cache@6998d139ddd3e68c71e9e398d8e40b71a2f39812
        with:
          path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Install Dependencies
        run: sudo apt-get install -y uchardet
      - name: Run Tests
        env:
          TEST: CODE
        run: test/run-test.sh
      # - name: Run Failure Webhook
      #   env:
      #     JOB_STATUS: ${{ job.status }}
      #     WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      #     HOOK_OS_NAME: ${{ runner.os }}
      #     WORKFLOW_NAME: ${{ github.workflow }}
      #   if: ${{ failure() }}
      #   run: |
      #     wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
      #     chmod +x send.sh
      #     ./send.sh failure $WEBHOOK_URL
  ExampleMap:
    runs-on: ubuntu-20.04
    needs:
    - PreFlight
    - DreamChecker
    if: needs.PreFlight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Setup Cache
        uses: actions/cache@6998d139ddd3e68c71e9e398d8e40b71a2f39812
        with:
          path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Download rust_g
        run: scripts/download_rust_g.sh
      - name: Install rust_g deps
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update || true
          sudo apt install libssl1.1:i386
          ldd librust_g.so
      - name: Run Tests
        env:
          TEST: MAP
          MAP_PATH: example
        run: test/run-test.sh
      # - name: Run Failure Webhook
      #   env:
      #     JOB_STATUS: ${{ job.status }}
      #     WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      #     HOOK_OS_NAME: ${{ runner.os }}
      #     WORKFLOW_NAME: ${{ github.workflow }}
      #   if: ${{ failure() }}
      #   run: |
      #     wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
      #     chmod +x send.sh
      #     ./send.sh failure $WEBHOOK_URL
  SierraMap:
    runs-on: ubuntu-20.04
    needs:
    - PreFlight
    - DreamChecker
    if: needs.PreFlight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Setup Cache
        uses: actions/cache@6998d139ddd3e68c71e9e398d8e40b71a2f39812
        with:
          path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Download rust_g
        run: scripts/download_rust_g.sh
      - name: Install rust_g deps
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update || true
          sudo apt install libssl1.1:i386
          ldd librust_g.so
      - name: Run Tests
        env:
          TEST: MAP
          MAP_PATH: sierra
        run: test/run-test.sh
      # - name: Run Failure Webhook
      #   env:
      #     JOB_STATUS: ${{ job.status }}
      #     WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      #     HOOK_OS_NAME: ${{ runner.os }}
      #     WORKFLOW_NAME: ${{ github.workflow }}
      #   if: ${{ failure() }}
      #   run: |
      #     wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
      #     chmod +x send.sh
      #     ./send.sh failure $WEBHOOK_URL
  AwaySites:
    runs-on: ubuntu-20.04
    needs:
    - PreFlight
    - DreamChecker
    if: needs.PreFlight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Setup Cache
        uses: actions/cache@6998d139ddd3e68c71e9e398d8e40b71a2f39812
        with:
          path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Download rust_g
        run: scripts/download_rust_g.sh
      - name: Install rust_g deps
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update || true
          sudo apt install libssl1.1:i386
          ldd librust_g.so
      - name: Run Tests
        env:
          TEST: MAP
          MAP_PATH: away_sites_testing
        run: test/run-test.sh
      # - name: Run Failure Webhook
      #   env:
      #     JOB_STATUS: ${{ job.status }}
      #     WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      #     HOOK_OS_NAME: ${{ runner.os }}
      #     WORKFLOW_NAME: ${{ github.workflow }}
      #   if: ${{ failure() }}
      #   run: |
      #     wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
      #     chmod +x send.sh
      #     ./send.sh failure $WEBHOOK_URL
